<?php
/**
* Implements hook_theme() to add the template definition.
**/
function verify_certificate_theme($existing, $type, $theme, $path) {
  return [
    'verify_certificate' => [
      'variables' => [
        'queryParams' => [],
        'candidateDetails' => [],
        'certDetails' => [],
        'coursedetails' => [],
        'coursedetailsdefault' => [],
        'verify' => 0
      ]
    ],
  ];
}
