<?php

use \Drupal\Core\Url;
use \Drupal\Core\Link;
use Drupal\node\Entity\Node;

/**
 * Implements hook_theme().
 */
function athena_course_theme($existing, $type, $theme, $path) {
  return [
    'course_banner' => [
      'variables' => [
      'course_title' => NULL,
      'ects_credit' => NULL,
      'univ_data' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      ],
    ],

    'courselist' => [
      'variables' => [
      'nodeid' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      ],
    ],

     'smotq' => [
      'variables' => [
      'source' => NULL,
      'campaign' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      ],
    ],



'smo' => [
      'variables' => [
      'course_title' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'source' => NULL,
      'campaign' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      'overview' => NULL,
      'testi' => NULL,
      'node' => NULL,
      'total_fee' => NULL,
      'course_team' => NULL,
      'faq' => NULL,
      'univ_data' => NULL,
      'course_title' => NULL,
      'why_course' => NULL,
      'duration' => NULL,
      'certification_label' => NULL,
      'certification' => NULL,
      'accreditations' => NULL,
      'course_details' => NULL,
      'course_modules' => NULL,
      'total_credits' => NULL,
      'academic_route' => NULL,
      'academic_route_desc' => NULL,
      'mature_entry_label' => NULL,
      'mature_entry_desc' => NULL,
      'language_prof_label' => NULL,
      'language_prof_desc' => NULL,
      'why_athena' => NULL,

      ],
    ],


     'discussions' => [
      'variables' => [
      'course_title' => NULL,
      'discussions' => NULL,
      'course_title' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      ],
    ],
     'discussions_detail' => [
      'variables' => [
      'course_title' => NULL,
      'discussion' => NULL,
      'post' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      ],
    ],
    'course_homepage_tabs' => [
      'variables' => [
      'academic' => NULL,
      'certifications' => NULL,
      'micro' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'acaddesc' => NULL,
      'microdesc' => NULL,
      'cerdesc' => NULL,
      'base_path' => NULL,
      ],
    ],

    'course_description_tabs' => [
      'variables' => [
      'overview' => NULL,
      'testi' => NULL,
      'node' => NULL,
      'total_fee' => NULL,
      'course_team' => NULL,
      'faq' => NULL,
      'univ_data' => NULL,
      'course_title' => NULL,
      'why_course' => NULL,
      'duration' => NULL,
      'certification_label' => NULL,
      'certification' => NULL,
      'accreditations' => NULL,
      'course_details' => NULL,
      'course_modules' => NULL,
      'total_credits' => NULL,
      'academic_route' => NULL,
      'academic_route_desc' => NULL,
      'mature_entry_label' => NULL,
      'mature_entry_desc' => NULL,
      'language_prof_label' => NULL,
      'language_prof_desc' => NULL,
      'why_athena' => NULL,
      'tax_value' => NULL,
      'base_path' => NULL,
      ],
    ],

    'course_search' => [
      'variables' => [
      'overview' => NULL,
      'node' => NULL,
      'count' => NULL,
      'duration' => NULL,
      'search_key' => NULL,
      'partner_list' => NULL,
      'accreditations' => NULL,
      'course_details' => NULL,
      'course_modules' => NULL,
      'total_credits' => NULL,
      'academic_route' => NULL,
      'academic_route_desc' => NULL,
      'mature_entry_label' => NULL,
      'mature_entry_desc' => NULL,
      'language_prof_label' => NULL,
      'language_prof_desc' => NULL,
      'why_athena' => NULL,
 'nids' => NULL,
      'base_path' => NULL,
      ],
    ],


 'course_academic' => [
      'variables' => [
      'overview' => NULL,
      'title1' => NULL,
      'title2' => NULL,
      'desc' => NULL,
      'header_image' => NULL,
      'paragraph' => NULL,
      'insig' => NULL,
      'course_list' => NULL,
      'course_details' => NULL,
      'course_modules' => NULL,
      'total_credits' => NULL,
      'academic_route' => NULL,
      'academic_route_desc' => NULL,
      'mature_entry_label' => NULL,
      'mature_entry_desc' => NULL,
      'language_prof_label' => NULL,
      'language_prof_desc' => NULL,
      'why_athena' => NULL,
 'nids' => NULL,
      'base_path' => NULL,
      ],
    ],
  'popular_course' => [
      'variables' => [
      'base_path' => NULL,
      'course' => NULL,
      ],
    ],
    'latest_insights_sidebar' => [
      'variables' => [
      'base_path' => NULL,
      'insig' => NULL,
      'popular' => NULL,
      'univ_popular' => NULL,
      ],
    ],
    'homepage_testimonials' => [
      'variables' => [
      'base_path' => NULL,
      'testi' => NULL,
      ],
    ],
    'coursepage_testimonials' => [
      'variables' => [
      'base_path' => NULL,
      'testi' => NULL,
      ],
    ],
    'popular_insights' => [
      'variables' => [
      'base_path' => NULL,
      'popu' => NULL,
      ],
    ],
    'mba_program_courses' => [
      'variables' => [
      'base_path' => NULL,
      'course' => NULL,
      ],
    ],

    'certification_program_courses' => [
      'variables' => [
      'base_path' => NULL,
      'course' => NULL,
      ],
    ],
    'event_page' => [
      'variables' => [
      'upcoming' => NULL,
      'past' => NULL,
      'base_path' => NULL,
      ],
    ],
    'course_registration' => [
      'variables' => [
      'base_path' => NULL,
      'source' => NULL,
      'campaign' => NULL,
      'cid' => NULL,
      'nodes' => NULL,
      ],
    ],
    'universities' => [
      'variables' => [
      'base_path' => NULL,
      'insig' => NULL,
      'last_insight' => NULL,
      'nodes' => NULL,
      ],
    ],

     'university' => [
      'variables' => [
      'base_path' => NULL,
      'data' => NULL,
      'univ_data' => NULL,
      'nodes' => NULL,
      ],
    ],


 'course_list' => [
      'variables' => [
      'base_path' => NULL,
      ],
    ],



  ];
}


function athena_course_page_attachments(array &$attachments) {
    $account = \Drupal::currentUser();
    if ($account->id() != 1) {
      $attachments['#attached']['library'][] = 'athena_course/cuddly-slider';
    }


    $route_name = \Drupal::routeMatch()->getRouteName();

    // Custom meta tags on smo and course pages.
    if ($route_name == 'athena_course.course' || $route_name == 'athena_smo.smo') {
      $possible_parameters = \Drupal::routeMatch()->getParameters();
      $possible_parameters_obj = $possible_parameters->all();
      $nid = $possible_parameters_obj['nid'];
      $node = Node::load($nid);
      $course_category = $node->get('field_course_category')->value;
      if ($course_category == 'Academic') {
        $field1 = 'field_course_page_meta_tag';
        $field2 = 'field_course_page_meta_descripti';
        $field3 = 'field_course_page_meta_keywords';
      }
      if ($course_category == 'Certifications') {
        $field1 = 'field_smo_page_meta_tag_title';
        $field2 = 'field_smo_page_meta_tag_descript';
        $field3 = 'field_smo_page_meta_tag_keywords';
      }
      $meta_tag_value = $node->get($field1)->value;
      $meta_tag_desc = $node->get($field2)->value;
      $meta_tag_keywords = array();
      foreach ($node->{$field3}->getValue() as $value) {
        if (!empty($value['value'])) {
          $meta_tag_keywords[] = $value['value'];
        }
      }
      if (count($meta_tag_keywords) > 0) {
        $meta_tag_keywords_list = implode(',', $meta_tag_keywords);
      }
      if (!empty($meta_tag_value)) {
        $attachments['#attached']['html_head'][] = [
          [
            '#type' => 'html_tag',
            '#tag' => 'title',
            '#value' => $meta_tag_value,
            '#weight' => -11,
          ],
          'title'
        ];
      }
      if (!empty($meta_tag_desc)) {
        $attachments['#attached']['html_head'][] = [
          [
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => [
              'name' => 'description',
              'content' => $meta_tag_desc
            ],
            '#weight' => -10,
          ],
          'desc'
        ];
      }
      if (!empty($meta_tag_keywords_list)) {
        $attachments['#attached']['html_head'][] = [
          [
            '#type' => 'html_tag',
            '#tag' => 'meta',
            '#attributes' => [
              'name' => 'keywords',
              'content' => $meta_tag_keywords_list
            ],
            '#weight' => -9,
          ],
          'keywords'
        ];
      }
    }

    if ($route_name == 'athena_course.StudentEnroltoCourse') {
      $from = $_REQUEST['from'] ?? '';
      $uid = $_REQUEST['UId'] ?? '';
      $cid = $_REQUEST['CId'] ?? '';
      $modId = $_REQUEST['ModId'] ?? '';
      $mail = $_REQUEST['mail'] ?? '';
      $source = $_REQUEST['source'] ?? '';
      if (!empty($cid)) {
        $referer = $_SERVER['HTTP_REFERER'];
        $enablePixel = TRUE;
        if ((strpos($referer, 'pgcertificateEnrol') !== false) || (strpos($referer, 'diplomaEnrol') !== false) ) {
            $enablePixel = FALSE;
        }

        if ($source == 'ShareASale' && $enablePixel) {
          // ShareASale Pixel.
          $shareASalePixel = '<img src="https://www.shareasale.com/sale.cfm?tracking=' . $uid . '&amount=0.00&merchantID=102553&transtype=lead" width="1" height="1">';
          $attachments['#attached']['html_head'][] = [
            [
              '#tag' => '',
              '#value' => \Drupal\Core\Render\Markup::create($shareASalePixel),
              '#weight' => 10,
            ],
            'shareasale'
          ];
        }

        if ($source == 'KWANKO') {
          // Kwanko Pixel.
          $kwankoPixel = '<img src="https://action.metaffiliation.com/trk.php?mclic=G51165D1011&argann=' . $uid . '&altid=' . $mail . '" width="1" height="1" border="0" />';
          $attachments['#attached']['html_head'][] = [
            [
              '#tag' => '',
              '#value' => \Drupal\Core\Render\Markup::create($kwankoPixel),
              '#weight' => 10,
            ],
            'kwanko'
          ];
        }

        if ($source == 'BIGTRUNK') {
          // Big Trunk Pixel.
          $bigTrunkPixel = '<img src="https://bigtrunk.o18.click/p?mid=3476&t=i&oid=7967214" width="0px" height="0px">';
          $attachments['#attached']['html_head'][] = [
            [
              '#tag' => '',
              '#value' => \Drupal\Core\Render\Markup::create($bigTrunkPixel),
              '#weight' => 10,
            ],
            'bigTrunk'
          ];
        }

        if (!empty($from) && $from == 'affiliate') {
          if (!empty($uid)) {
           $url = "https://ulearn.athena.edu/StudentEnroltoCourse?UId=$uid&CId=$cid&ModId=$modId&source=$source";
          }
          if (!empty($mail)) {
            $url = "https://ulearn.athena.edu/login?mail=$mail&CId=$cid&source=$source";
          }
        }
        else {
          $url = "https://ulearn.athena.edu/login?mail=$mail&CId=$cid&source=$source";
        }


        $redirect = "<meta http-equiv='refresh' content='3;url=$url' />";
        $attachments['#attached']['html_head'][] = [
          [
            '#tag' => '',
            '#value' => \Drupal\Core\Render\Markup::create($redirect),
            '#weight' => -10,
          ],
          'ulearn_redirect'
        ];

      }
    }
}

/**
 * Get University link.
 */

function get_university_link($awarding_body) {
    $univName = $awarding_body;
    $database = \Drupal::database();
    $query = $database->select('node_field_data', 'nfd');
    $query->leftJoin('node__field_university_key', 'nfu', 'nfu.entity_id = nfd.nid');
    $query->condition('nfd.title', $univName);
    $query->fields('nfu', ['field_university_key_value']);
    $result = $query->execute();
    $data = $result->fetchAll();
    $link = $awarding_body;
    if (count($data) > 0) {
      $dataArr = reset($data);
      $universitykey = $dataArr->field_university_key_value;
      $url = Url::fromRoute('athena_course.university', ['univ' => $universitykey]);
      $link = Link::fromTextAndUrl($awarding_body, $url);
    }
    return $link;
}

