<?php

use \Drupal\Core\Url;
use \Drupal\Core\Link;
/**
 * Implements hook_theme().
 */
function athena_course_theme($existing, $type, $theme, $path) {
  return [
    'course_banner' => [
      'variables' => [
      'course_title' => NULL,
      'ects_credit' => NULL,
      'univ_data' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      ],
    ],

    'courselist' => [
      'variables' => [
      'nodeid' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      ],
    ],

     'smotq' => [
      'variables' => [
      'source' => NULL,
      'campaign' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      ],
    ],



'smo' => [
      'variables' => [
      'course_title' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'source' => NULL,
      'campaign' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      'overview' => NULL,
      'testi' => NULL,
      'node' => NULL,
      'total_fee' => NULL,
      'course_team' => NULL,
      'faq' => NULL,
      'univ_data' => NULL,
      'course_title' => NULL,
      'why_course' => NULL,
      'duration' => NULL,
      'certification_label' => NULL,
      'certification' => NULL,
      'accreditations' => NULL,
      'course_details' => NULL,
      'course_modules' => NULL,
      'total_credits' => NULL,
      'academic_route' => NULL,
      'academic_route_desc' => NULL,
      'mature_entry_label' => NULL,
      'mature_entry_desc' => NULL,
      'language_prof_label' => NULL,
      'language_prof_desc' => NULL,
      'why_athena' => NULL,

      ],
    ],


     'discussions' => [
      'variables' => [
      'course_title' => NULL,
      'discussions' => NULL,
      'course_title' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      ],
    ],
     'discussions_detail' => [
      'variables' => [
      'course_title' => NULL,
      'discussion' => NULL,
      'post' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'base_path' => NULL,
      ],
    ],
    'course_homepage_tabs' => [
      'variables' => [
      'academic' => NULL,
      'certifications' => NULL,
      'micro' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      'acaddesc' => NULL,
      'microdesc' => NULL,
      'cerdesc' => NULL,
      'base_path' => NULL,
      ],
    ],

    'course_description_tabs' => [
      'variables' => [
      'overview' => NULL,
      'testi' => NULL,
      'node' => NULL,
      'total_fee' => NULL,
      'course_team' => NULL,
      'faq' => NULL,
      'univ_data' => NULL,
      'course_title' => NULL,
      'why_course' => NULL,
      'duration' => NULL,
      'certification_label' => NULL,
      'certification' => NULL,
      'accreditations' => NULL,
      'course_details' => NULL,
      'course_modules' => NULL,
      'total_credits' => NULL,
      'academic_route' => NULL,
      'academic_route_desc' => NULL,
      'mature_entry_label' => NULL,
      'mature_entry_desc' => NULL,
      'language_prof_label' => NULL,
      'language_prof_desc' => NULL,
      'why_athena' => NULL,
      'base_path' => NULL,
      ],
    ],

    'course_search' => [
      'variables' => [
      'overview' => NULL,
      'node' => NULL,
      'count' => NULL,
      'duration' => NULL,
      'search_key' => NULL,
      'partner_list' => NULL,
      'accreditations' => NULL,
      'course_details' => NULL,
      'course_modules' => NULL,
      'total_credits' => NULL,
      'academic_route' => NULL,
      'academic_route_desc' => NULL,
      'mature_entry_label' => NULL,
      'mature_entry_desc' => NULL,
      'language_prof_label' => NULL,
      'language_prof_desc' => NULL,
      'why_athena' => NULL,
 'nids' => NULL,
      'base_path' => NULL,
      ],
    ],


 'course_academic' => [
      'variables' => [
      'overview' => NULL,
      'title1' => NULL,
      'title2' => NULL,
      'desc' => NULL,
      'header_image' => NULL,
      'paragraph' => NULL,
      'insig' => NULL,
      'course_list' => NULL,
      'course_details' => NULL,
      'course_modules' => NULL,
      'total_credits' => NULL,
      'academic_route' => NULL,
      'academic_route_desc' => NULL,
      'mature_entry_label' => NULL,
      'mature_entry_desc' => NULL,
      'language_prof_label' => NULL,
      'language_prof_desc' => NULL,
      'why_athena' => NULL,
 'nids' => NULL,
      'base_path' => NULL,
      ],
    ],
  'popular_course' => [
      'variables' => [
      'base_path' => NULL,
      'course' => NULL,
      ],
    ],
    'latest_insights_sidebar' => [
      'variables' => [
      'base_path' => NULL,
      'insig' => NULL,
      'popular' => NULL,
      'univ_popular' => NULL,
      ],
    ],
    'homepage_testimonials' => [
      'variables' => [
      'base_path' => NULL,
      'testi' => NULL,
      ],
    ],
    'coursepage_testimonials' => [
      'variables' => [
      'base_path' => NULL,
      'testi' => NULL,
      ],
    ],
    'popular_insights' => [
      'variables' => [
      'base_path' => NULL,
      'popu' => NULL,
      ],
    ],
    'mba_program_courses' => [
      'variables' => [
      'base_path' => NULL,
      'course' => NULL,
      ],
    ],

    'certification_program_courses' => [
      'variables' => [
      'base_path' => NULL,
      'course' => NULL,
      ],
    ],
    'event_page' => [
      'variables' => [
      'upcoming' => NULL,
      'past' => NULL,
      'base_path' => NULL,
      ],
    ],
    'course_registration' => [
      'variables' => [
      'base_path' => NULL,
      'source' => NULL,
      'campaign' => NULL,
      'cid' => NULL,
      'nodes' => NULL,
      ],
    ],
    'universities' => [
      'variables' => [
      'base_path' => NULL,
      'insig' => NULL,
      'nodes' => NULL,
      ],
    ],

     'university' => [
      'variables' => [
      'base_path' => NULL,
      'data' => NULL,
      'univ_data' => NULL,
      'nodes' => NULL,
      ],
    ],


 'course_list' => [
      'variables' => [
      'base_path' => NULL,
      ],
    ],



  ];
}


function athena_course_page_attachments(array &$attachments) {
    $account = \Drupal::currentUser();
    if ($account->id() != 1) {
      $attachments['#attached']['library'][] = 'athena_course/cuddly-slider';
    }


    $route_name = \Drupal::routeMatch()->getRouteName();
    if ($route_name == 'athena_course.StudentEnroltoCourse') {
      $uid = $_REQUEST['UId'] ?? '';
      $cid = $_REQUEST['CId'] ?? '';
      $modId = $_REQUEST['ModId'] ?? '';
      $mail = $_REQUEST['mail'] ?? '';
      $source = $_REQUEST['source'] ?? '';
      if (!empty($cid)) {
        $shareASalePixel = '<img src="https://www.shareasale.com/sale.cfm?tracking=' . $uid . '&amount=0.00&merchantID=102553&transtype=lead" width="1" height="1">';
        $attachments['#attached']['html_head'][] = [
          [
            '#tag' => '',
            '#value' => \Drupal\Core\Render\Markup::create($shareASalePixel),
            '#weight' => 10,
          ],
          'shareasale'
        ];

        if (!empty($uid)) {
         $url = "https://ulearn.athena.edu/StudentEnroltoCourse?UId=$uid&CId=$cid&ModId=$modId&source=$source";
        }

        if (!empty($mail)) {
          $url = "https://ulearn.athena.edu/login?mail=$mail&CId=$cid&source=$source";
        }

        $redirect = "<meta http-equiv='refresh' content='3;url=$url' />";
        $attachments['#attached']['html_head'][] = [
          [
            '#tag' => '',
            '#value' => \Drupal\Core\Render\Markup::create($redirect),
            '#weight' => -10,
          ],
          'ulearn_redirect'
        ];

      }
    }
}

/**
 * Get University link.
 */

function get_university_link($awarding_body) {
    $univName = $awarding_body;
    $database = \Drupal::database();
    $query = $database->select('node_field_data', 'nfd');
    $query->leftJoin('node__field_university_key', 'nfu', 'nfu.entity_id = nfd.nid');
    $query->condition('nfd.title', $univName);
    $query->fields('nfu', ['field_university_key_value']);
    $result = $query->execute();
    $data = $result->fetchAll();
    $link = $awarding_body;
    if (count($data) > 0) {
      $dataArr = reset($data);
      $universitykey = $dataArr->field_university_key_value;
      $url = Url::fromRoute('athena_course.university', ['univ' => $universitykey]);
      $link = Link::fromTextAndUrl($awarding_body, $url);
    }
    return $link;
}

