<?php

/**
 * Implements hook_theme().
 */
function athena_course_theme($existing, $type, $theme, $path) {
  return [
    'course_banner' => [
      'variables' => [
      'course_title' => NULL,
      'ects_credit' => NULL,
      'awarding_body' => NULL,
      'description' => NULL,
      'category' => NULL,
      'banner' => NULL,
      'node' => NULL,
      ],
    ],
    
    'course_description_tabs' => [
      'variables' => [
      'overview' => NULL,
      'node' => NULL,
      'total_fee' => NULL,
      'duration' => NULL,
      'certification_label' => NULL,
      'certification' => NULL,
      'accreditations' => NULL,
      'course_details' => NULL,
      'course_modules' => NULL,
      'total_credits' => NULL,
      'academic_route' => NULL,
      'academic_route_desc' => NULL,
      'mature_entry_label' => NULL,
      'mature_entry_desc' => NULL,
      'language_prof_label' => NULL,
      'language_prof_desc' => NULL,
      'why_athena' => NULL,
      ],
    ],
    
  ];
}
